### ISSUE TITLE
Preview still shows author/image credit

### ISSUE THREAD

**Issue by troyrutter** [iastate/iastate22-wordpress#17]
Previewing a Draft post, shows the author name and image credit on the post even if the option is set to hide.

**Comment by kwickham** [comment]
For the preview, I don't believe meta data is sent to a preview page. I wouldn't expect any meta data would show in the 'preview' unless there's some fancy ACF integration that adds extra functionality. It is just a default WP behavior/bug for meta data. 
_**see**_ https://github.com/WordPress/gutenberg/issues/16006

I have gotten rid of the image credit in b910dc8

**Comment by troyrutter** [comment]
great thanks, this can be closed. I wasn't sure if it was possible. :)
