### ISSUE TITLE
Show/Hide post author no longer work on new posts

### ISSUE THREAD

**Issue by troyrutter** [iastate/iastate22-wordpress#21]
As of the latest version, toggling on the show/hide button on posts no longer hides the author/image credit.

In addition, the label and description of the button is a little awkward. It is labeled "show/hide" and then the toggle is yes or no. I assume if the toggle is set to YES, it should HIDE, so the label should actually just be "Hide post author" since the default will be No.   But, it can be read several ways. Suggest making it more clear after the functionality is fixed.

Older posts don't seem to be affected - I am guessing it has to do with a boolean value and the field now being in ACF. 

It's kind of important, since posts are a basic functionality - and I don't want my name on all the posts indefinitely. :)

**Comment by troyrutter** [comment]
show_author is always the value 1 even if i toggle it off/on

**Comment by troyrutter** [comment]
The same issue exists on the share this icons

**Comment by troyrutter** [comment]
@kwickham    I was able to solve the author issue by removing the hide_author metafield check in the or statement. Was that from a previous field?

	{% if post.meta('_meta_info') != 'hide_author' or post.show_author %}
to
	{% if post.show_author %}
	
	The share this one suddenly started working again, not sure why.

**Comment by kwickham** [comment]
`_meta_info` is a legacy fallback. We can get ride of some of these fallback bits in V2 but for now I have a fix pushed to Develop, 11d1947
